open CommonGrade
open Hw6_2

let _ = output (fun () -> 
  (parenize (NODE (NODE (NODE (LEAF Korea, LEAF France), LEAF Brazil), LEAF England))) = "(((Korea France) Brazil) England)")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Nigeria, (NODE (LEAF Argentina, (NODE (LEAF Italy, (NODE (LEAF Argentina, LEAF England)))))))), (NODE ((NODE (LEAF Germany, (NODE (LEAF Italy, LEAF Cameroon)))), LEAF Cameroon))))) = "((Nigeria (Argentina (Italy (Argentina England)))) ((Germany (Italy Cameroon)) Cameroon))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF England, LEAF Nigeria)), LEAF Poland)), (NODE (LEAF England, (NODE ((NODE (LEAF Sweden, LEAF England)), LEAF France))))))) = "(((England Nigeria) Poland) (England ((Sweden England) France)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Usa, LEAF Sweden)), (NODE (LEAF Argentina, LEAF Brazil)))), (NODE (LEAF Cameroon, LEAF France))))) = "(((Usa Sweden) (Argentina Brazil)) (Cameroon France))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Poland, LEAF England)), LEAF Italy)), (NODE ((NODE (LEAF Germany, LEAF Sweden)), (NODE (LEAF England, (NODE (LEAF Sweden, LEAF Italy))))))))) = "(((Poland England) Italy) ((Germany Sweden) (England (Sweden Italy))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Cameroon, LEAF Nigeria)), LEAF France)), (NODE (LEAF Cameroon, (NODE (LEAF Poland, LEAF Italy)))))), (NODE ((NODE (LEAF Poland, LEAF Portugal)), (NODE (LEAF Portugal, LEAF Norway))))))) = "((((Cameroon Nigeria) France) (Cameroon (Poland Italy))) ((Poland Portugal) (Portugal Norway)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Cameroon, LEAF Cameroon)), LEAF Usa)), LEAF France)), LEAF Usa))) = "((((Cameroon Cameroon) Usa) France) Usa)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Italy, (NODE (LEAF Korea, (NODE (LEAF Poland, LEAF Cameroon)))))), LEAF Argentina)), (NODE ((NODE (LEAF Nigeria, (NODE (LEAF Nigeria, LEAF Germany)))), (NODE (LEAF Italy, (NODE (LEAF Italy, LEAF Brazil))))))))) = "(((Italy (Korea (Poland Cameroon))) Argentina) ((Nigeria (Nigeria Germany)) (Italy (Italy Brazil))))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Brazil, (NODE ((NODE ((NODE (LEAF Nigeria, LEAF Poland)), LEAF Poland)), LEAF Norway)))), (NODE ((NODE (LEAF Usa, (NODE (LEAF Germany, LEAF Argentina)))), (NODE (LEAF Brazil, (NODE (LEAF Japan, LEAF Poland))))))))) = "((Brazil (((Nigeria Poland) Poland) Norway)) ((Usa (Germany Argentina)) (Brazil (Japan Poland))))")
let _ = output (fun () ->
(parenize (NODE (LEAF Korea, (NODE ((NODE ((NODE (LEAF Korea, LEAF Korea)), LEAF Sweden)), (NODE (LEAF Cameroon, LEAF Sweden))))))) = "(Korea (((Korea Korea) Sweden) (Cameroon Sweden)))")
let _ = output (fun () ->
(parenize (NODE (LEAF Norway, (NODE (LEAF Portugal, (NODE (LEAF France, (NODE (LEAF Usa, LEAF Argentina))))))))) = "(Norway (Portugal (France (Usa Argentina))))")
let _ = output (fun () ->
(parenize (NODE (LEAF Cameroon, (NODE ((NODE ((NODE ((NODE (LEAF Norway, LEAF Korea)), LEAF Norway)), LEAF Argentina)), LEAF Cameroon))))) = "(Cameroon ((((Norway Korea) Norway) Argentina) Cameroon))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Norway, LEAF Argentina)), (NODE (LEAF Portugal, LEAF Italy)))), (NODE (LEAF Korea, (NODE (LEAF Korea, LEAF Korea)))))), (NODE ((NODE ((NODE ((NODE (LEAF Portugal, LEAF Norway)), (NODE (LEAF Sweden, LEAF Norway)))), (NODE (LEAF Italy, (NODE (LEAF Italy, LEAF Korea)))))), (NODE ((NODE (LEAF Usa, LEAF Norway)), (NODE (LEAF Brazil, LEAF Germany))))))))) = "((((Norway Argentina) (Portugal Italy)) (Korea (Korea Korea))) ((((Portugal Norway) (Sweden Norway)) (Italy (Italy Korea))) ((Usa Norway) (Brazil Germany))))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Italy, (NODE (LEAF England, LEAF England)))), (NODE ((NODE (LEAF Portugal, LEAF Korea)), (NODE (LEAF Usa, LEAF Norway))))))) = "((Italy (England England)) ((Portugal Korea) (Usa Norway)))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Usa, (NODE (LEAF Japan, (NODE (LEAF Brazil, LEAF Argentina)))))), LEAF Nigeria))) = "((Usa (Japan (Brazil Argentina))) Nigeria)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Germany, LEAF Argentina)), (NODE (LEAF England, LEAF Nigeria)))), (NODE ((NODE (LEAF Brazil, LEAF Cameroon)), LEAF Argentina)))), (NODE ((NODE (LEAF Poland, (NODE (LEAF Korea, LEAF Italy)))), (NODE (LEAF France, (NODE ((NODE (LEAF Sweden, LEAF Brazil)), LEAF Italy))))))))) = "((((Germany Argentina) (England Nigeria)) ((Brazil Cameroon) Argentina)) ((Poland (Korea Italy)) (France ((Sweden Brazil) Italy))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Italy, LEAF Sweden)), LEAF England)), (NODE ((NODE (LEAF Usa, LEAF Japan)), LEAF England))))) = "(((Italy Sweden) England) ((Usa Japan) England))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Portugal, (NODE (LEAF Italy, LEAF Cameroon)))), LEAF Usa)), (NODE (LEAF Germany, LEAF France))))) = "(((Portugal (Italy Cameroon)) Usa) (Germany France))")
let _ = output (fun () ->
(parenize (NODE (LEAF Italy, LEAF Italy))) = "(Italy Italy)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Italy, LEAF Argentina)), (NODE (LEAF England, (NODE (LEAF Korea, LEAF Brazil)))))), LEAF Nigeria))) = "(((Italy Argentina) (England (Korea Brazil))) Nigeria)")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Cameroon, LEAF Norway)), (NODE ((NODE (LEAF France, LEAF Korea)), (NODE (LEAF Cameroon, LEAF Poland))))))) = "((Cameroon Norway) ((France Korea) (Cameroon Poland)))")
let _ = output (fun () ->
(parenize (NODE (LEAF Brazil, LEAF England))) = "(Brazil England)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Argentina, LEAF Norway)), (NODE (LEAF Germany, LEAF Nigeria)))), LEAF Italy))) = "(((Argentina Norway) (Germany Nigeria)) Italy)")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF England, LEAF Japan)), (NODE ((NODE (LEAF Brazil, LEAF Sweden)), LEAF Italy))))) = "((England Japan) ((Brazil Sweden) Italy))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Usa, (NODE (LEAF Japan, LEAF Cameroon)))), (NODE (LEAF Usa, LEAF Poland)))), (NODE ((NODE ((NODE (LEAF Cameroon, LEAF Italy)), LEAF England)), LEAF Brazil))))) = "(((Usa (Japan Cameroon)) (Usa Poland)) (((Cameroon Italy) England) Brazil))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Italy, (NODE (LEAF Sweden, (NODE (LEAF Norway, LEAF Germany)))))), (NODE ((NODE (LEAF Brazil, (NODE ((NODE (LEAF Norway, LEAF Brazil)), LEAF Sweden)))), (NODE ((NODE (LEAF France, (NODE (LEAF Poland, LEAF Japan)))), (NODE (LEAF Japan, LEAF Portugal))))))))) = "((Italy (Sweden (Norway Germany))) ((Brazil ((Norway Brazil) Sweden)) ((France (Poland Japan)) (Japan Portugal))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Sweden, (NODE (LEAF Cameroon, LEAF Poland)))), (NODE (LEAF Cameroon, (NODE (LEAF Korea, LEAF Poland)))))), (NODE ((NODE ((NODE (LEAF Portugal, LEAF England)), (NODE (LEAF Argentina, LEAF Sweden)))), (NODE ((NODE (LEAF England, LEAF Argentina)), LEAF Cameroon))))))) = "(((Sweden (Cameroon Poland)) (Cameroon (Korea Poland))) (((Portugal England) (Argentina Sweden)) ((England Argentina) Cameroon)))")
let _ = output (fun () ->
(parenize (NODE (LEAF Sweden, (NODE (LEAF Italy, (NODE ((NODE (LEAF Germany, (NODE (LEAF Sweden, LEAF Korea)))), LEAF Brazil))))))) = "(Sweden (Italy ((Germany (Sweden Korea)) Brazil)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Usa, LEAF Korea)), (NODE (LEAF Poland, (NODE (LEAF Korea, (NODE (LEAF Korea, LEAF France)))))))), (NODE (LEAF Germany, LEAF Brazil))))) = "(((Usa Korea) (Poland (Korea (Korea France)))) (Germany Brazil))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Argentina, LEAF Korea)), LEAF Usa)), LEAF Sweden))) = "(((Argentina Korea) Usa) Sweden)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Portugal, LEAF Usa)), (NODE (LEAF Nigeria, (NODE (LEAF Japan, LEAF Sweden)))))), LEAF Germany))) = "(((Portugal Usa) (Nigeria (Japan Sweden))) Germany)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Brazil, (NODE (LEAF Japan, LEAF Italy)))), LEAF Nigeria)), LEAF Usa)), LEAF Norway))) = "((((Brazil (Japan Italy)) Nigeria) Usa) Norway)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE ((NODE (LEAF Brazil, LEAF Japan)), LEAF Nigeria)), (NODE (LEAF Sweden, LEAF Norway)))), LEAF Portugal)), (NODE ((NODE ((NODE (LEAF Poland, LEAF Germany)), (NODE (LEAF Nigeria, LEAF Norway)))), LEAF Cameroon))))) = "(((((Brazil Japan) Nigeria) (Sweden Norway)) Portugal) (((Poland Germany) (Nigeria Norway)) Cameroon))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Usa, (NODE ((NODE (LEAF Korea, LEAF Germany)), LEAF Sweden)))), (NODE ((NODE ((NODE (LEAF Cameroon, (NODE (LEAF Argentina, LEAF Cameroon)))), (NODE (LEAF Brazil, LEAF Japan)))), (NODE (LEAF Germany, LEAF Germany))))))) = "((Usa ((Korea Germany) Sweden)) (((Cameroon (Argentina Cameroon)) (Brazil Japan)) (Germany Germany)))")
let _ = output (fun () ->
(parenize (NODE (LEAF Poland, (NODE ((NODE ((NODE (LEAF Poland, LEAF England)), LEAF Italy)), (NODE (LEAF Korea, (NODE (LEAF Cameroon, (NODE (LEAF Nigeria, LEAF Portugal))))))))))) = "(Poland (((Poland England) Italy) (Korea (Cameroon (Nigeria Portugal)))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Korea, (NODE (LEAF England, LEAF England)))), (NODE ((NODE (LEAF France, (NODE (LEAF France, LEAF Korea)))), LEAF Brazil)))), (NODE ((NODE ((NODE (LEAF France, LEAF Norway)), LEAF France)), LEAF Poland))))) = "(((Korea (England England)) ((France (France Korea)) Brazil)) (((France Norway) France) Poland))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Japan, (NODE (LEAF England, LEAF Italy)))), (NODE (LEAF Usa, (NODE ((NODE (LEAF Usa, LEAF Cameroon)), (NODE ((NODE (LEAF England, LEAF France)), LEAF Usa))))))))) = "((Japan (England Italy)) (Usa ((Usa Cameroon) ((England France) Usa))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF France, LEAF Usa)), LEAF Japan)), LEAF Poland))) = "(((France Usa) Japan) Poland)")
let _ = output (fun () ->
(parenize (NODE (LEAF Italy, LEAF Cameroon))) = "(Italy Cameroon)")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF France, LEAF Usa)), (NODE ((NODE ((NODE (LEAF Portugal, LEAF Brazil)), LEAF Nigeria)), LEAF Usa))))) = "((France Usa) (((Portugal Brazil) Nigeria) Usa))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Portugal, (NODE (LEAF Usa, LEAF England)))), LEAF France))) = "((Portugal (Usa England)) France)")
let _ = output (fun () ->
(parenize (NODE (LEAF Portugal, (NODE ((NODE (LEAF Norway, LEAF Korea)), (NODE ((NODE (LEAF Italy, LEAF Japan)), (NODE ((NODE (LEAF England, LEAF Japan)), LEAF Norway))))))))) = "(Portugal ((Norway Korea) ((Italy Japan) ((England Japan) Norway))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Argentina, LEAF Portugal)), LEAF Korea)), (NODE (LEAF Argentina, LEAF Usa)))), (NODE ((NODE (LEAF Usa, LEAF Cameroon)), LEAF Norway))))) = "((((Argentina Portugal) Korea) (Argentina Usa)) ((Usa Cameroon) Norway))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Nigeria, (NODE (LEAF Japan, LEAF Italy)))), (NODE (LEAF Cameroon, (NODE (LEAF Korea, LEAF Brazil)))))), (NODE (LEAF Nigeria, (NODE (LEAF Italy, LEAF Sweden)))))), (NODE ((NODE (LEAF Cameroon, (NODE ((NODE (LEAF Poland, LEAF Norway)), LEAF Portugal)))), LEAF France))))) = "((((Nigeria (Japan Italy)) (Cameroon (Korea Brazil))) (Nigeria (Italy Sweden))) ((Cameroon ((Poland Norway) Portugal)) France))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Portugal, LEAF Korea)), (NODE (LEAF Poland, (NODE (LEAF Norway, LEAF Nigeria)))))), (NODE ((NODE (LEAF Cameroon, LEAF Italy)), (NODE ((NODE (LEAF Nigeria, LEAF Sweden)), LEAF Germany))))))) = "(((Portugal Korea) (Poland (Norway Nigeria))) ((Cameroon Italy) ((Nigeria Sweden) Germany)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE ((NODE (LEAF Japan, LEAF Korea)), (NODE (LEAF Portugal, LEAF Norway)))), (NODE (LEAF Norway, LEAF Argentina)))), LEAF Sweden)), (NODE (LEAF Sweden, (NODE ((NODE (LEAF Brazil, LEAF Poland)), (NODE ((NODE (LEAF Norway, LEAF Germany)), LEAF Nigeria))))))))) = "(((((Japan Korea) (Portugal Norway)) (Norway Argentina)) Sweden) (Sweden ((Brazil Poland) ((Norway Germany) Nigeria))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Cameroon, (NODE (LEAF Italy, LEAF Argentina)))), LEAF Poland)), LEAF Cameroon)), (NODE (LEAF Italy, LEAF France))))) = "((((Cameroon (Italy Argentina)) Poland) Cameroon) (Italy France))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Italy, LEAF Italy)), (NODE (LEAF Korea, LEAF Poland)))), (NODE (LEAF Argentina, LEAF Sweden))))) = "(((Italy Italy) (Korea Poland)) (Argentina Sweden))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Nigeria, LEAF Germany)), (NODE ((NODE (LEAF Brazil, LEAF Germany)), LEAF Portugal))))) = "((Nigeria Germany) ((Brazil Germany) Portugal))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Italy, LEAF Italy)), (NODE (LEAF France, LEAF Cameroon)))), LEAF Nigeria)), (NODE (LEAF England, LEAF Usa))))) = "((((Italy Italy) (France Cameroon)) Nigeria) (England Usa))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Korea, (NODE (LEAF Italy, (NODE (LEAF Usa, LEAF France)))))), (NODE ((NODE (LEAF Italy, LEAF England)), LEAF Germany)))), (NODE ((NODE ((NODE (LEAF Norway, (NODE (LEAF Italy, LEAF England)))), LEAF Brazil)), LEAF Brazil))))) = "(((Korea (Italy (Usa France))) ((Italy England) Germany)) (((Norway (Italy England)) Brazil) Brazil))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF France, (NODE (LEAF Sweden, (NODE (LEAF Usa, LEAF Portugal)))))), (NODE ((NODE (LEAF Argentina, LEAF Germany)), (NODE ((NODE (LEAF England, LEAF Sweden)), LEAF Germany))))))) = "((France (Sweden (Usa Portugal))) ((Argentina Germany) ((England Sweden) Germany)))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Korea, LEAF Usa)), (NODE (LEAF Poland, (NODE (LEAF England, LEAF Cameroon))))))) = "((Korea Usa) (Poland (England Cameroon)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Italy, (NODE (LEAF Brazil, LEAF Poland)))), LEAF Portugal)), (NODE (LEAF England, LEAF Usa))))) = "(((Italy (Brazil Poland)) Portugal) (England Usa))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Italy, (NODE (LEAF Usa, LEAF Argentina)))), (NODE ((NODE (LEAF Italy, (NODE (LEAF England, (NODE (LEAF Brazil, LEAF France)))))), LEAF Nigeria))))) = "((Italy (Usa Argentina)) ((Italy (England (Brazil France))) Nigeria))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Sweden, LEAF Korea)), (NODE ((NODE (LEAF Portugal, LEAF Cameroon)), (NODE (LEAF Italy, LEAF Norway)))))), (NODE (LEAF Nigeria, LEAF France))))) = "(((Sweden Korea) ((Portugal Cameroon) (Italy Norway))) (Nigeria France))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF France, (NODE ((NODE (LEAF England, (NODE (LEAF Usa, LEAF Nigeria)))), (NODE (LEAF France, LEAF Sweden)))))), (NODE (LEAF Usa, (NODE (LEAF Portugal, LEAF Germany))))))) = "((France ((England (Usa Nigeria)) (France Sweden))) (Usa (Portugal Germany)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Argentina, (NODE (LEAF Italy, LEAF Cameroon)))), LEAF Sweden)), LEAF Italy)), (NODE ((NODE (LEAF England, (NODE ((NODE (LEAF Nigeria, LEAF Portugal)), LEAF Japan)))), (NODE ((NODE (LEAF England, LEAF France)), (NODE (LEAF Japan, LEAF Nigeria))))))))) = "((((Argentina (Italy Cameroon)) Sweden) Italy) ((England ((Nigeria Portugal) Japan)) ((England France) (Japan Nigeria))))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Nigeria, (NODE ((NODE (LEAF Poland, LEAF Norway)), LEAF Brazil)))), (NODE ((NODE ((NODE (LEAF Korea, LEAF Nigeria)), LEAF Germany)), (NODE ((NODE (LEAF Brazil, LEAF Portugal)), LEAF France))))))) = "((Nigeria ((Poland Norway) Brazil)) (((Korea Nigeria) Germany) ((Brazil Portugal) France)))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Argentina, (NODE ((NODE ((NODE (LEAF Italy, LEAF Norway)), LEAF Norway)), (NODE (LEAF Brazil, LEAF England)))))), LEAF Norway))) = "((Argentina (((Italy Norway) Norway) (Brazil England))) Norway)")
let _ = output (fun () ->
(parenize (NODE (LEAF Norway, (NODE ((NODE (LEAF Japan, (NODE (LEAF Usa, LEAF England)))), LEAF Korea))))) = "(Norway ((Japan (Usa England)) Korea))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Argentina, LEAF Japan)), LEAF Portugal)), (NODE ((NODE ((NODE ((NODE (LEAF Brazil, LEAF Portugal)), LEAF Portugal)), (NODE (LEAF Nigeria, LEAF Usa)))), (NODE ((NODE (LEAF Nigeria, LEAF Cameroon)), LEAF England))))))) = "(((Argentina Japan) Portugal) ((((Brazil Portugal) Portugal) (Nigeria Usa)) ((Nigeria Cameroon) England)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Norway, LEAF Poland)), LEAF Germany)), LEAF Korea))) = "(((Norway Poland) Germany) Korea)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Portugal, (NODE ((NODE (LEAF Cameroon, LEAF Italy)), LEAF Portugal)))), LEAF Japan)), (NODE ((NODE (LEAF Nigeria, LEAF Cameroon)), LEAF England))))) = "(((Portugal ((Cameroon Italy) Portugal)) Japan) ((Nigeria Cameroon) England))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Sweden, LEAF Cameroon)), LEAF Brazil)), (NODE (LEAF Italy, (NODE ((NODE (LEAF Norway, LEAF Cameroon)), LEAF Sweden)))))), LEAF Japan))) = "((((Sweden Cameroon) Brazil) (Italy ((Norway Cameroon) Sweden))) Japan)")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Brazil, (NODE ((NODE ((NODE (LEAF Italy, LEAF Argentina)), LEAF Cameroon)), LEAF Portugal)))), (NODE ((NODE (LEAF Italy, (NODE (LEAF Argentina, LEAF Usa)))), (NODE ((NODE (LEAF Germany, LEAF Sweden)), LEAF England))))))) = "((Brazil (((Italy Argentina) Cameroon) Portugal)) ((Italy (Argentina Usa)) ((Germany Sweden) England)))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Argentina, (NODE (LEAF France, LEAF Italy)))), (NODE ((NODE (LEAF Portugal, LEAF Poland)), (NODE (LEAF Argentina, (NODE ((NODE (LEAF France, LEAF Norway)), LEAF Poland))))))))) = "((Argentina (France Italy)) ((Portugal Poland) (Argentina ((France Norway) Poland))))")
let _ = output (fun () ->
(parenize (NODE (LEAF Poland, (NODE ((NODE ((NODE ((NODE (LEAF Italy, LEAF Japan)), LEAF Usa)), LEAF Norway)), (NODE (LEAF France, (NODE (LEAF Nigeria, LEAF Korea))))))))) = "(Poland ((((Italy Japan) Usa) Norway) (France (Nigeria Korea))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF England, LEAF England)), (NODE (LEAF Sweden, LEAF Norway)))), LEAF Poland))) = "(((England England) (Sweden Norway)) Poland)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Japan, LEAF Italy)), (NODE (LEAF Argentina, LEAF Norway)))), (NODE ((NODE (LEAF Norway, (NODE (LEAF Portugal, LEAF Cameroon)))), (NODE (LEAF Brazil, (NODE (LEAF Argentina, LEAF Portugal))))))))) = "(((Japan Italy) (Argentina Norway)) ((Norway (Portugal Cameroon)) (Brazil (Argentina Portugal))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Japan, LEAF Germany)), LEAF Sweden)), (NODE ((NODE ((NODE ((NODE (LEAF Italy, LEAF France)), (NODE (LEAF Portugal, LEAF Korea)))), (NODE (LEAF Usa, LEAF England)))), LEAF Italy))))) = "(((Japan Germany) Sweden) ((((Italy France) (Portugal Korea)) (Usa England)) Italy))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF England, (NODE (LEAF Norway, LEAF France)))), LEAF Korea)), (NODE ((NODE ((NODE (LEAF Portugal, LEAF Korea)), LEAF England)), (NODE (LEAF Cameroon, (NODE ((NODE (LEAF Japan, LEAF France)), LEAF Korea))))))))) = "(((England (Norway France)) Korea) (((Portugal Korea) England) (Cameroon ((Japan France) Korea))))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Argentina, LEAF France)), (NODE (LEAF France, (NODE (LEAF Japan, LEAF France))))))) = "((Argentina France) (France (Japan France)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF France, (NODE ((NODE (LEAF Norway, LEAF Nigeria)), (NODE (LEAF Usa, LEAF Italy)))))), LEAF England)), (NODE ((NODE (LEAF England, (NODE (LEAF Sweden, LEAF Brazil)))), LEAF Germany))))) = "(((France ((Norway Nigeria) (Usa Italy))) England) ((England (Sweden Brazil)) Germany))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Germany, (NODE ((NODE (LEAF France, LEAF Usa)), (NODE (LEAF Poland, LEAF England)))))), (NODE (LEAF England, LEAF Brazil)))), (NODE (LEAF Brazil, (NODE ((NODE (LEAF Portugal, LEAF Nigeria)), (NODE (LEAF France, LEAF Japan))))))))) = "(((Germany ((France Usa) (Poland England))) (England Brazil)) (Brazil ((Portugal Nigeria) (France Japan))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Cameroon, (NODE ((NODE (LEAF Brazil, LEAF Cameroon)), LEAF Brazil)))), (NODE (LEAF France, LEAF Korea)))), LEAF Germany))) = "(((Cameroon ((Brazil Cameroon) Brazil)) (France Korea)) Germany)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE ((NODE (LEAF Italy, LEAF Italy)), (NODE (LEAF France, LEAF Usa)))), LEAF Korea)), (NODE (LEAF Portugal, LEAF Brazil)))), LEAF Japan))) = "(((((Italy Italy) (France Usa)) Korea) (Portugal Brazil)) Japan)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Cameroon, LEAF Korea)), (NODE (LEAF Norway, LEAF Cameroon)))), (NODE (LEAF Cameroon, (NODE (LEAF Korea, LEAF Poland))))))) = "(((Cameroon Korea) (Norway Cameroon)) (Cameroon (Korea Poland)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Norway, LEAF France)), (NODE ((NODE ((NODE (LEAF Korea, LEAF Sweden)), LEAF Cameroon)), LEAF Portugal)))), (NODE ((NODE (LEAF England, LEAF Italy)), (NODE ((NODE ((NODE (LEAF Nigeria, LEAF Nigeria)), LEAF Cameroon)), LEAF Korea))))))) = "(((Norway France) (((Korea Sweden) Cameroon) Portugal)) ((England Italy) (((Nigeria Nigeria) Cameroon) Korea)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Japan, LEAF Japan)), (NODE (LEAF Nigeria, LEAF Cameroon)))), (NODE (LEAF Japan, (NODE (LEAF Sweden, LEAF Italy)))))), LEAF Norway))) = "((((Japan Japan) (Nigeria Cameroon)) (Japan (Sweden Italy))) Norway)")
let _ = output (fun () ->
(parenize (NODE (LEAF Korea, (NODE (LEAF England, (NODE (LEAF Usa, LEAF France))))))) = "(Korea (England (Usa France)))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Usa, (NODE ((NODE (LEAF Poland, LEAF Cameroon)), LEAF Brazil)))), (NODE (LEAF Germany, (NODE ((NODE ((NODE (LEAF Japan, LEAF Germany)), LEAF Italy)), LEAF Sweden))))))) = "((Usa ((Poland Cameroon) Brazil)) (Germany (((Japan Germany) Italy) Sweden)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Nigeria, LEAF England)), LEAF England)), (NODE (LEAF Korea, LEAF Usa)))), LEAF Cameroon))) = "((((Nigeria England) England) (Korea Usa)) Cameroon)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Cameroon, (NODE (LEAF Argentina, LEAF Portugal)))), (NODE ((NODE ((NODE (LEAF Sweden, LEAF Korea)), LEAF Japan)), LEAF Norway)))), (NODE ((NODE ((NODE (LEAF Argentina, (NODE (LEAF Argentina, LEAF Germany)))), (NODE ((NODE (LEAF Nigeria, LEAF Portugal)), LEAF Korea)))), LEAF Korea))))) = "(((Cameroon (Argentina Portugal)) (((Sweden Korea) Japan) Norway)) (((Argentina (Argentina Germany)) ((Nigeria Portugal) Korea)) Korea))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Brazil, LEAF Japan)), (NODE ((NODE (LEAF Brazil, LEAF Sweden)), (NODE ((NODE (LEAF Usa, LEAF Portugal)), LEAF Sweden))))))) = "((Brazil Japan) ((Brazil Sweden) ((Usa Portugal) Sweden)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Italy, (NODE (LEAF Japan, LEAF Cameroon)))), (NODE (LEAF England, LEAF France)))), (NODE ((NODE (LEAF France, LEAF Italy)), (NODE (LEAF Nigeria, LEAF Argentina))))))) = "(((Italy (Japan Cameroon)) (England France)) ((France Italy) (Nigeria Argentina)))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Argentina, (NODE ((NODE (LEAF Argentina, (NODE (LEAF Nigeria, LEAF Korea)))), (NODE (LEAF Norway, LEAF Argentina)))))), (NODE (LEAF Nigeria, LEAF Sweden))))) = "((Argentina ((Argentina (Nigeria Korea)) (Norway Argentina))) (Nigeria Sweden))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Sweden, (NODE (LEAF Argentina, LEAF Portugal)))), (NODE (LEAF France, LEAF Argentina))))) = "((Sweden (Argentina Portugal)) (France Argentina))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Nigeria, LEAF Cameroon)), (NODE ((NODE (LEAF Italy, LEAF Portugal)), (NODE (LEAF Italy, LEAF Brazil))))))) = "((Nigeria Cameroon) ((Italy Portugal) (Italy Brazil)))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Argentina, (NODE ((NODE (LEAF France, LEAF Cameroon)), LEAF Korea)))), (NODE (LEAF England, (NODE (LEAF Korea, (NODE (LEAF Norway, LEAF Japan)))))))), (NODE ((NODE (LEAF France, LEAF Norway)), (NODE (LEAF Argentina, (NODE (LEAF Cameroon, LEAF Italy))))))))) = "(((Argentina ((France Cameroon) Korea)) (England (Korea (Norway Japan)))) ((France Norway) (Argentina (Cameroon Italy))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Cameroon, (NODE (LEAF Nigeria, LEAF Cameroon)))), (NODE ((NODE ((NODE (LEAF Japan, LEAF Sweden)), (NODE (LEAF Korea, LEAF Germany)))), LEAF Brazil)))), (NODE (LEAF Japan, LEAF Germany))))) = "(((Cameroon (Nigeria Cameroon)) (((Japan Sweden) (Korea Germany)) Brazil)) (Japan Germany))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF France, LEAF Sweden)), LEAF Argentina)), (NODE (LEAF Portugal, (NODE (LEAF Cameroon, LEAF Usa))))))) = "(((France Sweden) Argentina) (Portugal (Cameroon Usa)))")
let _ = output (fun () ->
(parenize (NODE (LEAF Portugal, (NODE (LEAF Brazil, (NODE ((NODE (LEAF England, (NODE (LEAF Japan, LEAF Sweden)))), (NODE (LEAF Usa, LEAF Japan))))))))) = "(Portugal (Brazil ((England (Japan Sweden)) (Usa Japan))))")
let _ = output (fun () ->
(parenize (NODE (LEAF Usa, (NODE ((NODE (LEAF France, LEAF Italy)), (NODE (LEAF Portugal, (NODE (LEAF Cameroon, LEAF Argentina))))))))) = "(Usa ((France Italy) (Portugal (Cameroon Argentina))))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Italy, (NODE ((NODE ((NODE (LEAF Korea, LEAF England)), LEAF Poland)), LEAF Nigeria)))), (NODE ((NODE (LEAF Italy, LEAF England)), LEAF Argentina))))) = "((Italy (((Korea England) Poland) Nigeria)) ((Italy England) Argentina))")
let _ = output (fun () ->
(parenize (NODE (LEAF Germany, LEAF Japan))) = "(Germany Japan)")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Italy, LEAF England)), (NODE (LEAF Sweden, LEAF Italy)))), (NODE ((NODE (LEAF Sweden, LEAF Portugal)), (NODE ((NODE (LEAF Brazil, LEAF Japan)), (NODE (LEAF Norway, LEAF Norway))))))))) = "(((Italy England) (Sweden Italy)) ((Sweden Portugal) ((Brazil Japan) (Norway Norway))))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Cameroon, LEAF Brazil)), LEAF Usa)), (NODE (LEAF Argentina, LEAF Japan))))) = "(((Cameroon Brazil) Usa) (Argentina Japan))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE (LEAF Italy, (NODE (LEAF Japan, LEAF Poland)))), LEAF Germany)), (NODE ((NODE ((NODE (LEAF Portugal, (NODE (LEAF Korea, LEAF Korea)))), (NODE (LEAF Brazil, LEAF Cameroon)))), LEAF Usa))))) = "(((Italy (Japan Poland)) Germany) (((Portugal (Korea Korea)) (Brazil Cameroon)) Usa))")
let _ = output (fun () ->
(parenize (NODE ((NODE ((NODE ((NODE (LEAF Usa, LEAF Poland)), (NODE (LEAF Poland, LEAF Cameroon)))), LEAF Germany)), (NODE (LEAF Germany, (NODE (LEAF Cameroon, LEAF Germany))))))) = "((((Usa Poland) (Poland Cameroon)) Germany) (Germany (Cameroon Germany)))")
let _ = output (fun () ->
(parenize (NODE ((NODE (LEAF Brazil, (NODE ((NODE (LEAF France, LEAF Nigeria)), LEAF Usa)))), (NODE (LEAF Brazil, (NODE ((NODE (LEAF Korea, LEAF Cameroon)), LEAF Poland))))))) = "((Brazil ((France Nigeria) Usa)) (Brazil ((Korea Cameroon) Poland)))")
