open CommonGrade
open Hw6_4

let _ = output (fun () ->
  (eval (IMPLY (ORELSE (FALSE, LESS (NUM 0, (PLUS (NUM (-1), NUM 0)))), FALSE))))
let _ = output (fun () ->
(eval (ORELSE ((NOT ((ANDALSO (TRUE, FALSE)))), (IMPLY (TRUE, FALSE))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((ORELSE (TRUE, (NOT ((ORELSE (TRUE, (NOT (FALSE)))))))), (NOT (FALSE))))) = true)
let _ = output (fun () ->
(eval (NOT ((NOT ((ANDALSO ((LESS ((PLUS ((NUM 8), (NUM 60))), (PLUS ((NUM 4), (NUM 76))))), (NOT ((IMPLY (TRUE, TRUE))))))))))) = false)
let _ = output (fun () ->
(eval (IMPLY ((LESS ((PLUS ((NUM 74), (NUM 22))), (MINUS ((NUM 15), (NUM 37))))), (ORELSE ((LESS ((MINUS ((NUM 53), (NUM 68))), (PLUS ((NUM 48), (MINUS ((NUM 57), (NUM 89))))))), TRUE))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((IMPLY ((IMPLY ((ORELSE (FALSE, TRUE)), TRUE)), TRUE)), (ANDALSO (FALSE, (IMPLY (TRUE, TRUE))))))) = false)
let _ = output (fun () ->
(eval (LESS ((MINUS ((MINUS ((PLUS ((NUM 88), (NUM 12))), (PLUS ((NUM 33), (MINUS ((PLUS ((NUM 81), (PLUS ((NUM 67), (PLUS ((NUM 78), (PLUS ((NUM 73), (NUM 0))))))))), (NUM 13))))))), (MINUS ((NUM 42), (NUM 33))))), (MINUS ((PLUS ((NUM 42), (NUM 41))), (MINUS ((NUM 39), (PLUS ((PLUS ((NUM 76), (NUM 78))), (MINUS ((NUM 88), (NUM 88)))))))))))) = true)
let _ = output (fun () ->
(eval (ORELSE ((ANDALSO ((LESS ((MINUS ((NUM 97), (MINUS ((NUM 12), (NUM 61))))), (PLUS ((NUM 4), (NUM 27))))), (LESS ((NUM 69), (NUM 4))))), (LESS ((PLUS ((PLUS ((MINUS ((PLUS ((NUM 94), (NUM 28))), (PLUS ((NUM 53), (NUM 85))))), (NUM 20))), (PLUS ((NUM 72), (NUM 18))))), (PLUS ((NUM 50), (PLUS ((NUM 19), (NUM 15)))))))))) = false)
let _ = output (fun () ->
(eval (NOT ((LESS ((MINUS ((NUM 70), (PLUS ((NUM 79), (NUM 66))))), (NUM 96)))))) = false)
let _ = output (fun () ->
(eval (IMPLY ((LESS ((NUM 0), (PLUS ((NUM 90), (NUM 87))))), (LESS ((NUM 39), (MINUS ((PLUS ((NUM 74), (MINUS ((NUM 55), (NUM 74))))), (MINUS ((NUM 21), (NUM 20)))))))))) = true)
let _ = output (fun () ->
(eval (ORELSE ((IMPLY ((ANDALSO (TRUE, FALSE)), TRUE)), TRUE))) = true)
let _ = output (fun () ->
(eval (ANDALSO (FALSE, (IMPLY ((IMPLY (TRUE, (ANDALSO (FALSE, FALSE)))), TRUE))))) = false)
let _ = output (fun () ->
(eval (LESS ((MINUS ((MINUS ((NUM 24), (PLUS ((MINUS ((NUM 95), (NUM 10))), (MINUS ((NUM 3), (NUM 13))))))), (MINUS ((PLUS ((NUM 37), (NUM 73))), (NUM 34))))), (PLUS ((MINUS ((NUM 99), (MINUS ((MINUS ((MINUS ((NUM 82), (NUM 12))), (NUM 75))), (NUM 52))))), (PLUS ((NUM 97), (NUM 4)))))))) = true)
let _ = output (fun () ->
(eval (NOT ((ORELSE (TRUE, (LESS ((NUM 53), (MINUS ((NUM 21), (MINUS ((NUM 77), (NUM 25)))))))))))) = false)
let _ = output (fun () ->
(eval (ORELSE ((ANDALSO ((ANDALSO (FALSE, TRUE)), TRUE)), (IMPLY ((ANDALSO ((IMPLY (FALSE, TRUE)), FALSE)), TRUE))))) = true)
let _ = output (fun () ->
(eval (ANDALSO ((ORELSE ((IMPLY (TRUE, TRUE)), TRUE)), (NOT (FALSE))))) = true)
let _ = output (fun () ->
(eval (NOT (TRUE))) = false)
let _ = output (fun () ->
(eval (IMPLY (FALSE, (ANDALSO (TRUE, FALSE))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((ORELSE (FALSE, (LESS ((NUM 37), (MINUS ((NUM 3), (NUM 23))))))), (ORELSE ((LESS ((NUM 84), (NUM 71))), TRUE))))) = true)
let _ = output (fun () ->
(eval (LESS ((MINUS ((PLUS ((PLUS ((NUM 24), (MINUS ((MINUS ((NUM 27), (NUM 98))), (NUM 87))))), (PLUS ((NUM 81), (MINUS ((MINUS ((NUM 68), (NUM 62))), (NUM 38))))))), (PLUS ((PLUS ((MINUS ((PLUS ((NUM 21), (NUM 91))), (PLUS ((NUM 97), (PLUS ((NUM 55), (NUM 51))))))), (NUM 98))), (PLUS ((MINUS ((NUM 58), (NUM 86))), (PLUS ((MINUS ((MINUS ((NUM 13), (NUM 36))), (NUM 77))), (PLUS ((PLUS ((MINUS ((NUM 95), (NUM 59))), (NUM 50))), (NUM 70))))))))))), (NUM 21)))) = true)
let _ = output (fun () ->
(eval (NOT (FALSE))) = true)
let _ = output (fun () ->
(eval (LESS ((MINUS ((NUM 38), (MINUS ((PLUS ((NUM 20), (MINUS ((NUM 35), (PLUS ((MINUS ((PLUS ((NUM 5), (NUM 85))), (NUM 69))), (NUM 59))))))), (MINUS ((MINUS ((NUM 32), (MINUS ((PLUS ((NUM 38), (NUM 52))), (NUM 46))))), (NUM 64))))))), (NUM 81)))) = true)
let _ = output (fun () ->
(eval (IMPLY ((ANDALSO ((ORELSE (FALSE, TRUE)), (IMPLY (TRUE, TRUE)))), (ORELSE (TRUE, TRUE))))) = true)
let _ = output (fun () ->
(eval (NOT ((NOT ((NOT ((IMPLY ((ANDALSO (FALSE, FALSE)), TRUE))))))))) = false)
let _ = output (fun () ->
(eval (ORELSE (FALSE, (ANDALSO (TRUE, (IMPLY (FALSE, FALSE))))))) = true)
let _ = output (fun () ->
(eval (ORELSE (FALSE, (NOT ((LESS ((NUM 30), (NUM 10)))))))) = true)
let _ = output (fun () ->
(eval (NOT (TRUE))) = false)
let _ = output (fun () ->
(eval (ORELSE (FALSE, (IMPLY (TRUE, FALSE))))) = false)
let _ = output (fun () ->
(eval (ORELSE ((NOT ((NOT (FALSE)))), (ANDALSO (TRUE, (ORELSE ((IMPLY (TRUE, TRUE)), (IMPLY ((IMPLY (TRUE, FALSE)), FALSE))))))))) = true)
let _ = output (fun () ->
(eval (ANDALSO ((ANDALSO ((LESS ((NUM 48), (NUM 9))), (LESS ((NUM 69), (NUM 13))))), (IMPLY ((NOT ((IMPLY ((ANDALSO (TRUE, TRUE)), TRUE)))), FALSE))))) = false)
let _ = output (fun () ->
(eval (ORELSE ((ORELSE ((NOT (FALSE)), FALSE)), (ANDALSO (FALSE, (LESS ((NUM 98), (NUM 50)))))))) = true)
let _ = output (fun () ->
(eval (NOT ((LESS ((NUM 97), (MINUS ((NUM 39), (MINUS ((NUM 90), (MINUS ((NUM 39), (NUM 23)))))))))))) = true)
let _ = output (fun () ->
(eval (ORELSE ((NOT (FALSE)), FALSE))) = true)
let _ = output (fun () ->
(eval (IMPLY ((ORELSE ((LESS ((NUM 31), (MINUS ((NUM 9), (NUM 88))))), (IMPLY (FALSE, (NOT ((LESS ((NUM 55), (NUM 23))))))))), (ORELSE ((NOT ((IMPLY (TRUE, TRUE)))), (NOT (TRUE))))))) = false)
let _ = output (fun () ->
(eval (NOT (FALSE))) = true)
let _ = output (fun () ->
(eval (ORELSE ((ANDALSO ((ORELSE (FALSE, TRUE)), TRUE)), (IMPLY ((ANDALSO (TRUE, TRUE)), (ANDALSO (FALSE, FALSE))))))) = true)
let _ = output (fun () ->
(eval (LESS ((MINUS ((NUM 85), (PLUS ((PLUS ((MINUS ((NUM 41), (NUM 37))), (NUM 62))), (NUM 75))))), (NUM 83)))) = true)
let _ = output (fun () ->
(eval (ANDALSO (FALSE, (ANDALSO ((ANDALSO ((ANDALSO (TRUE, TRUE)), FALSE)), (IMPLY (TRUE, TRUE))))))) = false)
let _ = output (fun () ->
(eval (ORELSE ((ANDALSO ((ORELSE ((ORELSE (TRUE, TRUE)), (IMPLY (FALSE, FALSE)))), (ORELSE (FALSE, FALSE)))), (IMPLY (FALSE, (ANDALSO ((NOT (FALSE)), TRUE))))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((IMPLY (TRUE, (LESS ((NUM 40), (NUM 46))))), (LESS ((MINUS ((PLUS ((NUM 81), (MINUS ((NUM 13), (NUM 85))))), (NUM 30))), (MINUS ((NUM 99), (PLUS ((MINUS ((NUM 23), (NUM 52))), (NUM 48)))))))))) = true)
let _ = output (fun () ->
(eval (ORELSE ((ORELSE ((IMPLY (TRUE, TRUE)), (IMPLY (TRUE, (LESS ((PLUS ((NUM 48), (NUM 90))), (NUM 70))))))), TRUE))) = true)
let _ = output (fun () ->
(eval (IMPLY ((IMPLY ((ORELSE (FALSE, (ANDALSO (FALSE, (IMPLY (TRUE, TRUE)))))), (ANDALSO ((IMPLY ((ANDALSO (FALSE, TRUE)), TRUE)), (LESS ((MINUS ((NUM 96), (NUM 89))), (NUM 0))))))), (ORELSE (FALSE, FALSE))))) = false)
let _ = output (fun () ->
(eval (ANDALSO ((IMPLY (TRUE, (NOT ((ANDALSO (TRUE, TRUE)))))), (NOT ((NOT ((IMPLY (TRUE, FALSE))))))))) = false)
let _ = output (fun () ->
(eval (IMPLY ((NOT (TRUE)), (NOT (TRUE))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((NOT ((LESS ((NUM 65), (NUM 79))))), (NOT (TRUE))))) = true)
let _ = output (fun () ->
(eval (ANDALSO ((ORELSE (FALSE, TRUE)), (IMPLY ((ANDALSO (TRUE, (IMPLY (TRUE, TRUE)))), TRUE))))) = true)
let _ = output (fun () ->
(eval (ORELSE ((ORELSE ((ANDALSO (FALSE, (ORELSE (TRUE, (ORELSE (FALSE, TRUE)))))), (ANDALSO (FALSE, (ORELSE (FALSE, (LESS ((NUM 98), (NUM 33))))))))), (IMPLY ((NOT ((NOT (TRUE)))), (LESS ((NUM 0), (PLUS ((NUM 83), (NUM 99)))))))))) = true)
let _ = output (fun () ->
(eval (ORELSE ((ANDALSO ((IMPLY (TRUE, FALSE)), FALSE)), (NOT ((ANDALSO ((ANDALSO (TRUE, TRUE)), (IMPLY (TRUE, FALSE))))))))) = true)
let _ = output (fun () ->
(eval (NOT ((IMPLY (FALSE, (LESS ((MINUS ((NUM 18), (NUM 39))), (PLUS ((NUM 77), (NUM 34)))))))))) = false)
let _ = output (fun () ->
(eval (ANDALSO ((ORELSE (FALSE, TRUE)), (ANDALSO ((IMPLY ((NOT (FALSE)), FALSE)), TRUE))))) = false)
let _ = output (fun () ->
(eval (ORELSE ((LESS ((NUM 80), (MINUS ((NUM 92), (NUM 15))))), (IMPLY ((NOT (TRUE)), (ORELSE ((IMPLY (TRUE, FALSE)), (ORELSE (TRUE, (NOT (TRUE))))))))))) = true)
let _ = output (fun () ->
(eval (ANDALSO ((ANDALSO (FALSE, (IMPLY (TRUE, (ANDALSO (TRUE, (ANDALSO (FALSE, FALSE)))))))), TRUE))) = false)
let _ = output (fun () ->
(eval (NOT (FALSE))) = true)
let _ = output (fun () ->
(eval (LESS ((PLUS ((PLUS ((PLUS ((NUM 42), (NUM 46))), (NUM 86))), (NUM 21))), (PLUS ((PLUS ((PLUS ((NUM 61), (NUM 80))), (NUM 23))), (PLUS ((PLUS ((PLUS ((NUM 50), (PLUS ((NUM 40), (PLUS ((NUM 70), (NUM 24))))))), (MINUS ((MINUS ((NUM 40), (NUM 99))), (NUM 62))))), (MINUS ((NUM 11), (PLUS ((NUM 27), (NUM 14)))))))))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((IMPLY ((NOT (TRUE)), FALSE)), (NOT ((NOT (TRUE))))))) = true)
let _ = output (fun () ->
(eval (LESS ((PLUS ((NUM 61), (MINUS ((NUM 4), (NUM 68))))), (MINUS ((NUM 97), (NUM 62)))))) = true)
let _ = output (fun () ->
(eval (NOT ((ORELSE ((IMPLY ((ORELSE (FALSE, FALSE)), FALSE)), TRUE))))) = false)
let _ = output (fun () ->
(eval (ANDALSO ((ANDALSO (TRUE, (IMPLY (FALSE, TRUE)))), FALSE))) = false)
let _ = output (fun () ->
(eval (LESS ((NUM 57), (PLUS ((MINUS ((PLUS ((NUM 49), (PLUS ((NUM 4), (MINUS ((NUM 58), (NUM 34))))))), (PLUS ((MINUS ((NUM 33), (NUM 10))), (MINUS ((MINUS ((NUM 35), (NUM 28))), (NUM 36))))))), (NUM 73)))))) = true)
let _ = output (fun () ->
(eval (NOT ((NOT (TRUE))))) = true)
let _ = output (fun () ->
(eval (LESS ((PLUS ((PLUS ((NUM 93), (NUM 80))), (MINUS ((NUM 62), (MINUS ((PLUS ((PLUS ((NUM 38), (MINUS ((NUM 1), (NUM 13))))), (NUM 15))), (MINUS ((PLUS ((PLUS ((NUM 85), (NUM 76))), (NUM 83))), (NUM 31))))))))), (MINUS ((MINUS ((NUM 21), (NUM 14))), (PLUS ((NUM 44), (PLUS ((NUM 94), (NUM 54)))))))))) = false)
let _ = output (fun () ->
(eval (LESS ((PLUS ((MINUS ((MINUS ((NUM 67), (PLUS ((NUM 19), (NUM 49))))), (PLUS ((NUM 46), (MINUS ((PLUS ((NUM 0), (NUM 28))), (NUM 58))))))), (NUM 58))), (MINUS ((NUM 55), (PLUS ((MINUS ((PLUS ((MINUS ((PLUS ((NUM 79), (NUM 95))), (NUM 48))), (NUM 55))), (NUM 41))), (PLUS ((PLUS ((NUM 44), (NUM 67))), (MINUS ((NUM 73), (NUM 67)))))))))))) = false)
let _ = output (fun () ->
(eval (LESS ((NUM 49), (MINUS ((NUM 71), (NUM 57)))))) = false)
let _ = output (fun () ->
(eval (IMPLY ((ANDALSO (TRUE, (ORELSE ((LESS ((MINUS ((NUM 74), (NUM 4))), (NUM 30))), (NOT ((LESS ((NUM 82), (NUM 20))))))))), (ANDALSO ((NOT ((LESS ((NUM 99), (MINUS ((NUM 65), (NUM 59))))))), (NOT (TRUE))))))) = false)
let _ = output (fun () ->
(eval (ANDALSO ((ANDALSO ((ANDALSO (FALSE, FALSE)), (ORELSE (FALSE, TRUE)))), (ANDALSO ((ANDALSO (TRUE, FALSE)), FALSE))))) = false)
let _ = output (fun () ->
(eval (ORELSE ((NOT (FALSE)), TRUE))) = true)
let _ = output (fun () ->
(eval (ORELSE ((LESS ((MINUS ((NUM 10), (PLUS ((PLUS ((NUM 74), (NUM 63))), (NUM 18))))), (PLUS ((NUM 18), (PLUS ((MINUS ((NUM 7), (PLUS ((NUM 52), (NUM 13))))), (NUM 72))))))), (IMPLY ((ANDALSO ((IMPLY (FALSE, FALSE)), (NOT ((LESS ((NUM 36), (NUM 89))))))), TRUE))))) = true)
let _ = output (fun () ->
(eval (ANDALSO ((ANDALSO ((ORELSE (FALSE, (IMPLY ((ANDALSO (FALSE, FALSE)), TRUE)))), (IMPLY ((LESS ((MINUS ((NUM 21), (NUM 57))), (NUM 4))), FALSE)))), (ANDALSO ((LESS ((NUM 72), (PLUS ((MINUS ((MINUS ((NUM 62), (NUM 14))), (NUM 43))), (MINUS ((NUM 52), (NUM 16))))))), TRUE))))) = false)
let _ = output (fun () ->
(eval (NOT ((IMPLY (FALSE, FALSE))))) = false)
let _ = output (fun () ->
(eval (ANDALSO ((ANDALSO (TRUE, (ORELSE (TRUE, FALSE)))), (NOT ((NOT ((ORELSE ((IMPLY (FALSE, TRUE)), FALSE))))))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((ANDALSO (FALSE, TRUE)), TRUE))) = true)
let _ = output (fun () ->
(eval (ORELSE ((ORELSE (FALSE, (ORELSE (FALSE, FALSE)))), (ORELSE (TRUE, (IMPLY (FALSE, FALSE))))))) = true)
let _ = output (fun () ->
(eval (NOT ((LESS ((NUM 25), (NUM 45)))))) = false)
let _ = output (fun () ->
(eval (LESS ((NUM 80), (MINUS ((PLUS ((PLUS ((MINUS ((NUM 32), (NUM 97))), (NUM 81))), (NUM 20))), (MINUS ((MINUS ((NUM 10), (MINUS ((NUM 26), (PLUS ((NUM 32), (MINUS ((NUM 10), (NUM 58))))))))), (NUM 88)))))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((NOT (TRUE)), (ANDALSO ((ORELSE ((ORELSE (TRUE, FALSE)), (ORELSE (TRUE, (NOT (FALSE)))))), (ORELSE ((ORELSE (TRUE, FALSE)), TRUE))))))) = true)
let _ = output (fun () ->
(eval (ORELSE ((LESS ((NUM 0), (MINUS ((PLUS ((NUM 40), (NUM 58))), (PLUS ((MINUS ((PLUS ((NUM 44), (NUM 37))), (NUM 52))), (MINUS ((MINUS ((NUM 92), (NUM 84))), (NUM 83))))))))), (NOT ((NOT ((IMPLY (TRUE, FALSE))))))))) = true)
let _ = output (fun () ->
(eval (LESS ((NUM 44), (PLUS ((PLUS ((NUM 7), (NUM 78))), (NUM 89)))))) = true)
let _ = output (fun () ->
(eval (ANDALSO ((NOT ((IMPLY (TRUE, TRUE)))), (LESS ((PLUS ((NUM 9), (PLUS ((NUM 71), (PLUS ((NUM 68), (NUM 22))))))), (NUM 43)))))) = false)
let _ = output (fun () ->
(eval (NOT ((NOT ((ANDALSO ((ORELSE (TRUE, (IMPLY (TRUE, FALSE)))), (IMPLY (TRUE, TRUE))))))))) = true)
let _ = output (fun () ->
(eval (LESS ((NUM 61), (NUM 16)))) = false)
let _ = output (fun () ->
(eval (NOT ((NOT ((ORELSE (TRUE, (LESS ((NUM 93), (NUM 44)))))))))) = true)
let _ = output (fun () ->
(eval (NOT ((NOT ((NOT (TRUE))))))) = false)
let _ = output (fun () ->
(eval (NOT ((LESS ((PLUS ((PLUS ((NUM 71), (MINUS ((NUM 60), (MINUS ((NUM 3), (NUM 91))))))), (NUM 49))), (NUM 86)))))) = true)
let _ = output (fun () ->
(eval (LESS ((PLUS ((PLUS ((MINUS ((MINUS ((NUM 78), (NUM 40))), (NUM 6))), (MINUS ((NUM 43), (MINUS ((NUM 53), (NUM 11))))))), (NUM 11))), (MINUS ((MINUS ((NUM 94), (MINUS ((MINUS ((PLUS ((MINUS ((NUM 37), (NUM 57))), (PLUS ((NUM 0), (NUM 27))))), (MINUS ((NUM 31), (NUM 31))))), (PLUS ((NUM 39), (PLUS ((NUM 35), (NUM 21))))))))), (MINUS ((NUM 86), (NUM 58)))))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((LESS ((PLUS ((MINUS ((MINUS ((NUM 20), (PLUS ((NUM 4), (NUM 93))))), (PLUS ((NUM 98), (NUM 78))))), (NUM 11))), (PLUS ((NUM 77), (NUM 4))))), FALSE))) = false)
let _ = output (fun () ->
(eval (ORELSE ((ANDALSO ((NOT (FALSE)), (LESS ((MINUS ((NUM 86), (NUM 87))), (PLUS ((MINUS ((NUM 96), (NUM 11))), (NUM 32))))))), (LESS ((PLUS ((NUM 74), (MINUS ((MINUS ((NUM 74), (NUM 95))), (MINUS ((NUM 70), (NUM 92))))))), (NUM 89)))))) = true)
let _ = output (fun () ->
(eval (LESS ((NUM 83), (NUM 73)))) = false)
let _ = output (fun () ->
(eval (ANDALSO ((LESS ((NUM 75), (PLUS ((NUM 78), (PLUS ((NUM 10), (NUM 79))))))), (ORELSE (FALSE, (ANDALSO (FALSE, TRUE))))))) = false)
let _ = output (fun () ->
(eval (LESS ((NUM 66), (MINUS ((NUM 38), (MINUS ((MINUS ((PLUS ((PLUS ((PLUS ((NUM 2), (NUM 74))), (NUM 34))), (PLUS ((NUM 80), (MINUS ((NUM 32), (NUM 97))))))), (PLUS ((NUM 35), (PLUS ((NUM 28), (NUM 52))))))), (PLUS ((PLUS ((MINUS ((NUM 39), (MINUS ((NUM 46), (NUM 29))))), (NUM 67))), (MINUS ((NUM 19), (NUM 74)))))))))))) = false)
let _ = output (fun () ->
(eval (ORELSE ((ANDALSO ((IMPLY (FALSE, (ANDALSO (TRUE, (IMPLY (FALSE, TRUE)))))), TRUE)), TRUE))) = true)
let _ = output (fun () ->
(eval (IMPLY (TRUE, (LESS ((NUM 19), (PLUS ((PLUS ((NUM 3), (NUM 79))), (NUM 48)))))))) = true)
let _ = output (fun () ->
(eval (LESS ((MINUS ((NUM 12), (PLUS ((NUM 63), (MINUS ((NUM 25), (MINUS ((MINUS ((NUM 47), (PLUS ((NUM 47), (NUM 60))))), (NUM 83))))))))), (MINUS ((MINUS ((PLUS ((NUM 64), (PLUS ((NUM 4), (NUM 86))))), (MINUS ((PLUS ((NUM 71), (NUM 75))), (NUM 64))))), (PLUS ((PLUS ((MINUS ((MINUS ((NUM 69), (NUM 31))), (NUM 25))), (NUM 39))), (NUM 14)))))))) = true)
let _ = output (fun () ->
(eval (IMPLY ((NOT ((IMPLY (TRUE, TRUE)))), (NOT ((LESS ((MINUS ((NUM 98), (NUM 77))), (PLUS ((NUM 6), (NUM 37)))))))))) = true)
let _ = output (fun () ->
(eval (ORELSE ((ORELSE ((NOT (TRUE)), (ANDALSO (TRUE, TRUE)))), (NOT ((LESS ((NUM 41), (PLUS ((NUM 56), (PLUS ((NUM 21), (NUM 76)))))))))))) = true)
let _ = output (fun () ->
(eval (LESS ((MINUS ((MINUS ((NUM 7), (MINUS ((NUM 88), (PLUS ((PLUS ((NUM 57), (MINUS ((PLUS ((NUM 72), (NUM 64))), (PLUS ((NUM 68), (NUM 55))))))), (MINUS ((NUM 25), (PLUS ((MINUS ((NUM 41), (NUM 30))), (NUM 79))))))))))), (MINUS ((MINUS ((NUM 17), (NUM 31))), (NUM 15))))), (PLUS ((NUM 23), (PLUS ((MINUS ((NUM 49), (MINUS ((NUM 11), (PLUS ((NUM 95), (MINUS ((NUM 17), (MINUS ((NUM 16), (MINUS ((NUM 40), (NUM 32))))))))))))), (NUM 51)))))))) = true)
let _ = output (fun () ->
(eval (LESS ((MINUS ((MINUS ((MINUS ((NUM 29), (NUM 17))), (MINUS ((NUM 36), (MINUS ((NUM 96), (NUM 56))))))), (PLUS ((NUM 89), (MINUS ((NUM 53), (NUM 65))))))), (NUM 99)))) = true)
let _ = output (fun () ->
(eval (ANDALSO ((NOT (TRUE)), (IMPLY (TRUE, (ANDALSO (FALSE, TRUE))))))) = false)
let _ = output (fun () ->
(eval (ORELSE ((LESS ((MINUS ((MINUS ((PLUS ((NUM 12), (NUM 80))), (NUM 9))), (NUM 81))), (NUM 17))), (NOT (TRUE))))) = true)
let _ = output (fun () ->
(eval (ANDALSO (TRUE, (ORELSE (FALSE, FALSE))))) = false)
let _ = output (fun () ->
(eval (ANDALSO ((LESS ((MINUS ((NUM 81), (NUM 17))), (NUM 15))), (LESS ((NUM 50), (PLUS ((PLUS ((NUM 93), (PLUS ((PLUS ((MINUS ((NUM 7), (NUM 61))), (NUM 38))), (NUM 46))))), (PLUS ((NUM 57), (PLUS ((NUM 13), (MINUS ((NUM 95), (NUM 28)))))))))))))) = false)
let _ = output (fun () ->
(eval (IMPLY ((NOT ((IMPLY (FALSE, (LESS ((NUM 49), (PLUS ((NUM 26), (NUM 40))))))))), (ANDALSO ((ORELSE ((LESS ((NUM 77), (PLUS ((NUM 74), (NUM 50))))), (IMPLY (TRUE, (ANDALSO (TRUE, FALSE)))))), (NOT (FALSE))))))) = true)
