open CommonGrade
open Hw6_3

let _ = output (fun () ->
  (drop (NODE (NODE (NODE (LEAF Korea, LEAF France), LEAF Brazil), LEAF England)) England) =
  "((Korea France) Brazil)")

let _ = output (fun () ->
  (drop (NODE (NODE (NODE (LEAF Korea, LEAF France), LEAF Brazil), LEAF England)) France) =
  "((Korea Brazil) England)")

let _ = output (fun () ->
  (drop (NODE (NODE (NODE (LEAF Korea, LEAF France), LEAF Brazil), LEAF England)) Brazil) =
  "((Korea France) England)")

let _ = output (fun () ->
(drop (NODE (LEAF Usa, NODE (LEAF Korea, NODE (LEAF Brazil, NODE (LEAF Usa, NODE (LEAF France, LEAF Sweden)))))) Germany) = "(Usa (Korea (Brazil (Usa (France Sweden)))))")
let _ = output (fun () ->
(drop (NODE (LEAF France, LEAF Nigeria)) Sweden) = "(France Nigeria)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Germany, LEAF Germany), LEAF Italy)) Portugal) = "((Germany Germany) Italy)")
let _ = output (fun () ->
(drop (NODE (LEAF Brazil, LEAF Germany)) Japan) = "(Brazil Germany)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Portugal, NODE (LEAF Poland, LEAF Japan)), NODE (NODE (NODE (NODE (LEAF Germany, LEAF Sweden), LEAF Korea), NODE (LEAF Portugal, LEAF Sweden)), LEAF Italy))) Sweden) = "((Portugal (Poland Japan)) (((Germany Korea) Portugal) Italy))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (LEAF France, NODE (LEAF Argentina, LEAF Italy)), LEAF Germany), NODE (NODE (LEAF Sweden, LEAF Korea), NODE (LEAF Germany, LEAF Portugal))), NODE (LEAF Argentina, LEAF Argentina))) Usa) = "((((France (Argentina Italy)) Germany) ((Sweden Korea) (Germany Portugal))) (Argentina Argentina))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF England, NODE (NODE (LEAF Portugal, LEAF Nigeria), NODE (LEAF England, LEAF Korea))), LEAF Cameroon), NODE (NODE (LEAF England, LEAF Japan), LEAF Cameroon))) France) = "(((England ((Portugal Nigeria) (England Korea))) Cameroon) ((England Japan) Cameroon))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Germany, NODE (NODE (LEAF Cameroon, LEAF England), NODE (LEAF France, LEAF Korea))), NODE (LEAF Argentina, NODE (NODE (LEAF Germany, LEAF Nigeria), LEAF Nigeria)))) Italy) = "((Germany ((Cameroon England) (France Korea))) (Argentina ((Germany Nigeria) Nigeria)))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Brazil, LEAF Germany), LEAF France)) Korea) = "((Brazil Germany) France)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Cameroon, LEAF Nigeria), LEAF Japan)) Italy) = "((Cameroon Nigeria) Japan)")
let _ = output (fun () ->
(drop (NODE (LEAF Sweden, NODE (NODE (LEAF England, LEAF Norway), LEAF Nigeria))) Argentina) = "(Sweden ((England Norway) Nigeria))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Cameroon, LEAF Japan), LEAF Portugal)) Norway) = "((Cameroon Japan) Portugal)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Usa, LEAF Cameroon), LEAF Japan)) Sweden) = "((Usa Cameroon) Japan)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Korea, NODE (LEAF Usa, LEAF Portugal)), NODE (NODE (NODE (LEAF Nigeria, LEAF Cameroon), LEAF Germany), NODE (NODE (LEAF England, NODE (LEAF England, LEAF Poland)), NODE (LEAF Portugal, LEAF Argentina))))) Portugal) = "((Korea Usa) (((Nigeria Cameroon) Germany) ((England (England Poland)) ( Argentina))))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Korea, LEAF Usa), NODE (LEAF England, NODE (LEAF Italy, NODE (NODE (LEAF Brazil, LEAF Korea), LEAF Sweden))))) Brazil) = "((Korea Usa) (England (Italy (( Korea) Sweden))))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Nigeria, LEAF England), NODE (NODE (LEAF Usa, NODE (LEAF Portugal, LEAF Cameroon)), NODE (LEAF Norway, LEAF Italy)))) Brazil) = "((Nigeria England) ((Usa (Portugal Cameroon)) (Norway Italy)))")
let _ = output (fun () ->
(drop (NODE (LEAF Korea, NODE (LEAF Italy, NODE (LEAF Poland, LEAF Italy)))) Germany) = "(Korea (Italy (Poland Italy)))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Portugal, NODE (LEAF Portugal, LEAF Usa)), NODE (NODE (LEAF Portugal, LEAF France), LEAF Italy)), NODE (NODE (LEAF Cameroon, LEAF England), LEAF Brazil))) Poland) = "(((Portugal (Portugal Usa)) ((Portugal France) Italy)) ((Cameroon England) Brazil))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Sweden, NODE (LEAF Argentina, NODE (LEAF Norway, LEAF Poland))), NODE (NODE (LEAF Portugal, LEAF Nigeria), LEAF England))) Brazil) = "((Sweden (Argentina (Norway Poland))) ((Portugal Nigeria) England))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Norway, NODE (LEAF Sweden, LEAF Argentina)), NODE (NODE (LEAF Poland, LEAF Korea), NODE (NODE (LEAF Cameroon, LEAF France), LEAF France))), NODE (NODE (LEAF Nigeria, NODE (LEAF Germany, NODE (LEAF Brazil, LEAF France))), LEAF Norway))) Portugal) = "(((Norway (Sweden Argentina)) ((Poland Korea) ((Cameroon France) France))) ((Nigeria (Germany (Brazil France))) Norway))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Japan, LEAF Cameroon), NODE (LEAF England, NODE (NODE (LEAF Poland, LEAF Portugal), LEAF Italy)))) Sweden) = "((Japan Cameroon) (England ((Poland Portugal) Italy)))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Brazil, NODE (NODE (LEAF Japan, LEAF Korea), NODE (LEAF Cameroon, NODE (LEAF England, LEAF Italy)))), NODE (NODE (LEAF Poland, LEAF Sweden), LEAF Germany))) Portugal) = "((Brazil ((Japan Korea) (Cameroon (England Italy)))) ((Poland Sweden) Germany))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Argentina, LEAF Norway), NODE (LEAF Japan, NODE (LEAF Nigeria, NODE (LEAF Nigeria, LEAF France)))), NODE (LEAF Argentina, NODE (LEAF Brazil, LEAF Portugal)))) Germany) = "(((Argentina Norway) (Japan (Nigeria (Nigeria France)))) (Argentina (Brazil Portugal)))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Portugal, NODE (LEAF England, LEAF Nigeria)), NODE (LEAF Japan, LEAF England))) Germany) = "((Portugal (England Nigeria)) (Japan England))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Nigeria, NODE (LEAF Cameroon, NODE (NODE (LEAF Portugal, LEAF Sweden), LEAF Argentina))), LEAF Korea)) Germany) = "((Nigeria (Cameroon ((Portugal Sweden) Argentina))) Korea)")
let _ = output (fun () ->
(drop (NODE (LEAF Korea, NODE (LEAF Korea, LEAF Japan))) Cameroon) = "(Korea (Korea Japan))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Japan, NODE (LEAF Brazil, NODE (LEAF Norway, LEAF Sweden))), NODE (NODE (LEAF Argentina, NODE (LEAF Argentina, LEAF Italy)), LEAF Poland)), NODE (NODE (LEAF Nigeria, NODE (LEAF Nigeria, LEAF France)), LEAF Poland))) Italy) = "(((Japan (Brazil (Norway Sweden))) ((Argentina Argentina) Poland)) ((Nigeria (Nigeria France)) Poland))")
let _ = output (fun () ->
(drop (NODE (LEAF Usa, LEAF Germany)) Italy) = "(Usa Germany)")
let _ = output (fun () ->
(drop (NODE (LEAF Japan, NODE (LEAF Norway, NODE (LEAF Germany, LEAF Korea)))) Norway) = "(Japan (Germany Korea))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (NODE (LEAF Portugal, LEAF Nigeria), LEAF Sweden), NODE (LEAF Nigeria, LEAF Italy)), LEAF Poland), NODE (NODE (NODE (LEAF Cameroon, LEAF England), NODE (LEAF Brazil, NODE (LEAF Poland, LEAF Usa))), LEAF Usa))) Brazil) = "(((((Portugal Nigeria) Sweden) (Nigeria Italy)) Poland) (((Cameroon England) (Poland Usa)) Usa))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Korea, NODE (LEAF France, NODE (LEAF Korea, LEAF Argentina))), NODE (LEAF Italy, LEAF Norway)), LEAF Usa)) France) = "(((Korea (Korea Argentina)) (Italy Norway)) Usa)")
let _ = output (fun () ->
(drop (NODE (LEAF Argentina, NODE (NODE (LEAF Usa, LEAF Norway), NODE (LEAF Nigeria, NODE (LEAF Korea, LEAF Cameroon))))) Korea) = "(Argentina ((Usa Norway) (Nigeria ( Cameroon))))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Sweden, LEAF England), NODE (NODE (LEAF Argentina, LEAF Usa), LEAF Poland))) Japan) = "((Sweden England) ((Argentina Usa) Poland))")
let _ = output (fun () ->
(drop (NODE (LEAF England, NODE (LEAF Usa, LEAF Japan))) Sweden) = "(England (Usa Japan))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Italy, LEAF Japan), NODE (LEAF Portugal, LEAF Brazil)), NODE (LEAF Italy, LEAF Korea))) Cameroon) = "(((Italy Japan) (Portugal Brazil)) (Italy Korea))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF France, NODE (LEAF Sweden, LEAF Nigeria)), NODE (NODE (NODE (LEAF Poland, LEAF Japan), LEAF Portugal), LEAF Argentina)), NODE (LEAF Cameroon, NODE (NODE (LEAF France, LEAF Korea), LEAF France)))) Japan) = "(((France (Sweden Nigeria)) ((Poland Portugal) Argentina)) (Cameroon ((France Korea) France)))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF England, LEAF England), NODE (LEAF Korea, LEAF England)), NODE (LEAF Japan, NODE (LEAF Korea, NODE (LEAF Sweden, LEAF Argentina))))) Korea) = "(((England England) ( England)) (Japan (Sweden Argentina)))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF France, NODE (NODE (LEAF Germany, LEAF England), LEAF Italy)), LEAF Poland)) Cameroon) = "((France ((Germany England) Italy)) Poland)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (NODE (LEAF Korea, LEAF England), LEAF Korea), NODE (LEAF Korea, LEAF Usa)), LEAF Usa), NODE (NODE (LEAF Norway, LEAF Brazil), LEAF Poland))) Brazil) = "(((((Korea England) Korea) (Korea Usa)) Usa) (Norway Poland))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (LEAF Korea, LEAF Norway), NODE (LEAF Sweden, NODE (LEAF France, LEAF Argentina))), LEAF Korea), NODE (LEAF England, NODE (LEAF Usa, NODE (NODE (LEAF France, LEAF Poland), LEAF Germany))))) Portugal) = "((((Korea Norway) (Sweden (France Argentina))) Korea) (England (Usa ((France Poland) Germany))))")
let _ = output (fun () ->
(drop (NODE (LEAF Portugal, LEAF Sweden)) Sweden) = "Portugal")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Nigeria, NODE (LEAF Portugal, NODE (LEAF England, LEAF France))), LEAF Italy), NODE (NODE (LEAF Usa, LEAF Germany), LEAF Sweden))) Nigeria) = "(((Portugal (England France)) Italy) ((Usa Germany) Sweden))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Argentina, LEAF France), LEAF France), NODE (LEAF Cameroon, NODE (NODE (LEAF Poland, NODE (LEAF Argentina, LEAF Norway)), LEAF Japan)))) Korea) = "(((Argentina France) France) (Cameroon ((Poland (Argentina Norway)) Japan)))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF France, LEAF Usa), NODE (LEAF Cameroon, NODE (LEAF Brazil, LEAF Sweden))), NODE (LEAF Germany, NODE (LEAF Sweden, LEAF Poland)))) Japan) = "(((France Usa) (Cameroon (Brazil Sweden))) (Germany (Sweden Poland)))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Norway, NODE (NODE (LEAF Cameroon, LEAF Cameroon), NODE (LEAF Japan, LEAF Germany))), NODE (NODE (NODE (LEAF Norway, LEAF Argentina), LEAF Argentina), LEAF Korea)), NODE (NODE (NODE (LEAF Japan, LEAF Nigeria), NODE (NODE (LEAF Poland, LEAF Japan), LEAF Norway)), LEAF Germany))) Usa) = "(((Norway ((Cameroon Cameroon) (Japan Germany))) (((Norway Argentina) Argentina) Korea)) (((Japan Nigeria) ((Poland Japan) Norway)) Germany))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF France, LEAF Japan), LEAF Norway), LEAF Sweden)) Germany) = "(((France Japan) Norway) Sweden)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Germany, LEAF Norway), NODE (NODE (LEAF Italy, NODE (NODE (LEAF Usa, LEAF Brazil), NODE (LEAF Korea, LEAF Poland))), LEAF Argentina))) Korea) = "((Germany Norway) ((Italy ((Usa Brazil) ( Poland))) Argentina))")
let _ = output (fun () ->
(drop (NODE (LEAF France, NODE (NODE (LEAF Norway, LEAF France), NODE (LEAF Sweden, NODE (LEAF Cameroon, LEAF Italy))))) Japan) = "(France ((Norway France) (Sweden (Cameroon Italy))))")
let _ = output (fun () ->
(drop (NODE (LEAF Poland, LEAF Poland)) England) = "(Poland Poland)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Japan, NODE (LEAF England, LEAF Usa)), LEAF Nigeria), LEAF Sweden)) Portugal) = "(((Japan (England Usa)) Nigeria) Sweden)")
let _ = output (fun () ->
(drop (NODE (LEAF Germany, LEAF Korea)) Poland) = "(Germany Korea)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Japan, LEAF Poland), NODE (LEAF Usa, LEAF Usa)), NODE (NODE (NODE (LEAF Brazil, NODE (LEAF Norway, LEAF Norway)), LEAF Germany), NODE (LEAF Sweden, LEAF Sweden)))) Italy) = "(((Japan Poland) (Usa Usa)) (((Brazil (Norway Norway)) Germany) (Sweden Sweden)))")
let _ = output (fun () ->
(drop (NODE (LEAF Brazil, LEAF Brazil)) Germany) = "(Brazil Brazil)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Norway, LEAF Cameroon), LEAF Usa), NODE (LEAF Japan, LEAF England))) Brazil) = "(((Norway Cameroon) Usa) (Japan England))")
let _ = output (fun () ->
(drop (NODE (LEAF Portugal, LEAF Usa)) Poland) = "(Portugal Usa)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Nigeria, NODE (LEAF Brazil, LEAF England)), LEAF Cameroon)) Korea) = "((Nigeria (Brazil England)) Cameroon)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Usa, LEAF Korea), LEAF Sweden), NODE (NODE (LEAF Sweden, LEAF France), NODE (LEAF Brazil, LEAF Brazil)))) Argentina) = "(((Usa Korea) Sweden) ((Sweden France) (Brazil Brazil)))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Italy, LEAF Sweden), NODE (NODE (LEAF Poland, NODE (LEAF Sweden, NODE (LEAF Usa, LEAF Cameroon))), NODE (LEAF Korea, NODE (NODE (LEAF Italy, LEAF Sweden), LEAF Brazil))))) Poland) = "((Italy Sweden) ((Sweden (Usa Cameroon)) (Korea ((Italy Sweden) Brazil))))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Argentina, NODE (LEAF Nigeria, LEAF Germany)), NODE (NODE (LEAF Poland, LEAF Poland), NODE (LEAF England, NODE (LEAF France, LEAF Korea)))), NODE (NODE (LEAF Korea, LEAF Brazil), NODE (NODE (LEAF Korea, LEAF Norway), NODE (LEAF France, LEAF Italy))))) Germany) = "(((Argentina Nigeria) ((Poland Poland) (England (France Korea)))) ((Korea Brazil) ((Korea Norway) (France Italy))))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Korea, NODE (NODE (LEAF Sweden, LEAF Korea), LEAF France)), NODE (LEAF Korea, NODE (LEAF Sweden, LEAF Italy))), NODE (LEAF Usa, NODE (NODE (LEAF Argentina, LEAF Usa), LEAF Cameroon)))) France) = "(((Korea (Sweden Korea)) (Korea (Sweden Italy))) (Usa ((Argentina Usa) Cameroon)))")
let _ = output (fun () ->
(drop (NODE (LEAF Argentina, NODE (LEAF Germany, NODE (LEAF France, LEAF Brazil)))) Germany) = "(Argentina (France Brazil))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Sweden, LEAF England), NODE (NODE (NODE (LEAF Japan, LEAF Argentina), LEAF Brazil), NODE (NODE (LEAF Usa, LEAF France), NODE (LEAF Japan, NODE (LEAF Sweden, LEAF Sweden)))))) Norway) = "((Sweden England) (((Japan Argentina) Brazil) ((Usa France) (Japan (Sweden Sweden)))))")
let _ = output (fun () ->
(drop (NODE (LEAF Italy, NODE (LEAF Norway, LEAF Argentina))) Norway) = "(Italy ( Argentina))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Italy, LEAF Usa), NODE (LEAF Usa, NODE (LEAF Cameroon, LEAF England))), NODE (LEAF Sweden, LEAF Poland))) France) = "(((Italy Usa) (Usa (Cameroon England))) (Sweden Poland))")
let _ = output (fun () ->
(drop (NODE (LEAF Portugal, NODE (NODE (LEAF Italy, LEAF Korea), LEAF Cameroon))) Poland) = "(Portugal ((Italy Korea) Cameroon))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Nigeria, LEAF Sweden), NODE (LEAF Usa, NODE (LEAF Portugal, LEAF Poland))), NODE (NODE (NODE (LEAF Poland, NODE (LEAF France, LEAF France)), LEAF Cameroon), LEAF England))) Portugal) = "(((Nigeria Sweden) (Usa ( Poland))) (((Poland (France France)) Cameroon) England))")
let _ = output (fun () ->
(drop (NODE (LEAF Argentina, NODE (LEAF Nigeria, LEAF Usa))) Nigeria) = "(Argentina ( Usa))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Cameroon, LEAF Cameroon), NODE (LEAF Korea, NODE (LEAF Korea, NODE (LEAF Japan, LEAF Germany)))), NODE (NODE (LEAF Argentina, LEAF Usa), LEAF Brazil))) Italy) = "(((Cameroon Cameroon) (Korea (Korea (Japan Germany)))) ((Argentina Usa) Brazil))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF France, LEAF Korea), NODE (LEAF Portugal, LEAF Sweden))) Argentina) = "((France Korea) (Portugal Sweden))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Portugal, LEAF Germany), LEAF Usa), NODE (NODE (LEAF Nigeria, LEAF Germany), LEAF Italy))) Cameroon) = "(((Portugal Germany) Usa) ((Nigeria Germany) Italy))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Sweden, NODE (LEAF Cameroon, LEAF Brazil)), NODE (LEAF Norway, NODE (LEAF Nigeria, LEAF Portugal)))) Sweden) = "((Cameroon Brazil) (Norway (Nigeria Portugal)))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF France, NODE (LEAF Nigeria, LEAF France)), NODE (LEAF Korea, LEAF Germany)), LEAF Norway)) Nigeria) = "(((France ( France)) (Korea Germany)) Norway)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Germany, LEAF Norway), NODE (NODE (LEAF Brazil, LEAF Sweden), LEAF Japan)), NODE (NODE (NODE (LEAF Brazil, LEAF Portugal), LEAF Brazil), NODE (NODE (LEAF Argentina, LEAF England), NODE (LEAF France, LEAF England))))) Japan) = "(((Germany Norway) (Brazil Sweden)) (((Brazil Portugal) Brazil) ((Argentina England) (France England))))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Korea, LEAF Usa), NODE (NODE (LEAF Poland, LEAF Portugal), NODE (LEAF Portugal, LEAF Brazil))), NODE (LEAF Portugal, NODE (LEAF Poland, LEAF Sweden)))) Nigeria) = "(((Korea Usa) ((Poland Portugal) (Portugal Brazil))) (Portugal (Poland Sweden)))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Norway, LEAF Sweden), NODE (LEAF Argentina, LEAF England)), NODE (LEAF Nigeria, LEAF Nigeria))) Japan) = "(((Norway Sweden) (Argentina England)) (Nigeria Nigeria))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Norway, NODE (LEAF Portugal, LEAF Germany)), NODE (NODE (NODE (LEAF Italy, LEAF England), LEAF Japan), LEAF Germany))) Italy) = "((Norway (Portugal Germany)) ((( England) Japan) Germany))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Nigeria, NODE (LEAF England, LEAF Portugal)), NODE (LEAF Cameroon, LEAF Sweden))) Sweden) = "((Nigeria (England Portugal)) Cameroon)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (LEAF Brazil, NODE (LEAF Sweden, LEAF Poland)), LEAF Argentina), LEAF Portugal), NODE (NODE (NODE (NODE (LEAF Portugal, LEAF England), LEAF Cameroon), LEAF Sweden), LEAF England))) Sweden) = "((((Brazil ( Poland)) Argentina) Portugal) (((Portugal England) Cameroon) England))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Germany, LEAF Norway), NODE (LEAF Argentina, NODE (NODE (LEAF Sweden, LEAF Germany), NODE (LEAF Cameroon, LEAF Norway)))), NODE (LEAF England, LEAF France))) Cameroon) = "(((Germany Norway) (Argentina ((Sweden Germany) ( Norway)))) (England France))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF France, LEAF Portugal), NODE (LEAF Japan, NODE (LEAF France, NODE (NODE (LEAF Sweden, LEAF Poland), LEAF Nigeria))))) Brazil) = "((France Portugal) (Japan (France ((Sweden Poland) Nigeria))))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (NODE (LEAF Argentina, LEAF France), LEAF Italy), NODE (LEAF Italy, LEAF Germany)), LEAF Norway), NODE (LEAF Portugal, NODE (NODE (LEAF England, NODE (LEAF Japan, LEAF Sweden)), NODE (LEAF Japan, NODE (LEAF Italy, LEAF Norway)))))) Sweden) = "(((((Argentina France) Italy) (Italy Germany)) Norway) (Portugal ((England Japan) (Japan (Italy Norway)))))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF England, LEAF Nigeria), NODE (LEAF Argentina, NODE (LEAF Portugal, LEAF England))), NODE (NODE (NODE (LEAF England, LEAF Italy), LEAF Sweden), NODE (NODE (LEAF Sweden, LEAF Korea), NODE (LEAF Poland, LEAF Argentina))))) Nigeria) = "((England (Argentina (Portugal England))) (((England Italy) Sweden) ((Sweden Korea) (Poland Argentina))))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Sweden, NODE (LEAF Usa, LEAF Portugal)), NODE (NODE (LEAF Nigeria, LEAF France), NODE (NODE (LEAF Italy, LEAF Argentina), LEAF Nigeria))), LEAF Nigeria)) Korea) = "(((Sweden (Usa Portugal)) ((Nigeria France) ((Italy Argentina) Nigeria))) Nigeria)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (LEAF Norway, NODE (LEAF Cameroon, LEAF Germany)), LEAF Germany), NODE (LEAF Sweden, LEAF Japan)), LEAF Sweden)) Poland) = "((((Norway (Cameroon Germany)) Germany) (Sweden Japan)) Sweden)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Italy, LEAF Korea), NODE (NODE (NODE (LEAF Germany, LEAF Brazil), NODE (NODE (LEAF France, LEAF Sweden), LEAF Germany)), NODE (LEAF Brazil, NODE (LEAF Sweden, LEAF Japan))))) Argentina) = "((Italy Korea) (((Germany Brazil) ((France Sweden) Germany)) (Brazil (Sweden Japan))))")
let _ = output (fun () ->
(drop (NODE (LEAF Germany, LEAF Korea)) Poland) = "(Germany Korea)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Korea, LEAF Japan), NODE (LEAF Nigeria, NODE (LEAF Germany, LEAF France))), LEAF Cameroon)) Korea) = "((( Japan) (Nigeria (Germany France))) Cameroon)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Norway, NODE (LEAF England, NODE (NODE (LEAF France, LEAF Norway), LEAF Brazil))), LEAF Poland)) Italy) = "((Norway (England ((France Norway) Brazil))) Poland)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Sweden, LEAF Portugal), NODE (LEAF Brazil, NODE (LEAF Japan, LEAF Brazil)))) Argentina) = "((Sweden Portugal) (Brazil (Japan Brazil)))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Nigeria, LEAF Italy), NODE (NODE (LEAF France, NODE (LEAF Norway, LEAF Germany)), NODE (LEAF Italy, LEAF Usa)))) Norway) = "((Nigeria Italy) ((France ( Germany)) (Italy Usa)))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (NODE (LEAF Germany, LEAF Nigeria), LEAF Korea), LEAF France), LEAF Brazil), NODE (LEAF France, LEAF Usa))) England) = "(((((Germany Nigeria) Korea) France) Brazil) (France Usa))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Usa, NODE (LEAF Norway, NODE (LEAF Portugal, LEAF Poland))), NODE (LEAF Portugal, NODE (LEAF Brazil, LEAF Nigeria))), NODE (LEAF Usa, NODE (LEAF Korea, LEAF England)))) Norway) = "(((Usa (Portugal Poland)) (Portugal (Brazil Nigeria))) (Usa (Korea England)))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Poland, NODE (LEAF France, LEAF Portugal)), LEAF Germany), NODE (LEAF Argentina, LEAF Japan))) Usa) = "(((Poland (France Portugal)) Germany) (Argentina Japan))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Korea, NODE (LEAF England, NODE (LEAF France, LEAF Japan))), LEAF Nigeria)) Germany) = "((Korea (England (France Japan))) Nigeria)")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Brazil, NODE (LEAF Norway, LEAF Korea)), NODE (LEAF Sweden, NODE (LEAF Poland, NODE (LEAF Sweden, LEAF Germany))))) Portugal) = "((Brazil (Norway Korea)) (Sweden (Poland (Sweden Germany))))")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (LEAF Norway, LEAF Italy), NODE (NODE (LEAF Usa, LEAF Cameroon), LEAF Italy)), NODE (LEAF Poland, LEAF Germany))) England) = "(((Norway Italy) ((Usa Cameroon) Italy)) (Poland Germany))")
let _ = output (fun () ->
(drop (NODE (NODE (LEAF Portugal, NODE (NODE (LEAF Norway, NODE (LEAF Brazil, LEAF Usa)), NODE (LEAF Japan, LEAF Brazil))), NODE (NODE (LEAF France, LEAF Portugal), NODE (LEAF Usa, LEAF Japan)))) Korea) = "((Portugal ((Norway (Brazil Usa)) (Japan Brazil))) ((France Portugal) (Usa Japan)))")
let _ = output (fun () ->
(drop (NODE (LEAF Cameroon, NODE (LEAF Japan, LEAF Japan))) Poland) = "(Cameroon (Japan Japan))")
let _ = output (fun () ->
(drop (NODE (LEAF Cameroon, LEAF England)) Nigeria) = "(Cameroon England)")
let _ = output (fun () ->
(drop (NODE (NODE (NODE (NODE (LEAF Nigeria, LEAF Norway), NODE (NODE (LEAF Poland, LEAF Sweden), LEAF Nigeria)), NODE (NODE (LEAF Sweden, LEAF Sweden), LEAF Sweden)), NODE (NODE (LEAF Germany, LEAF Korea), LEAF Sweden))) Italy) = "((((Nigeria Norway) ((Poland Sweden) Nigeria)) ((Sweden Sweden) Sweden)) ((Germany Korea) Sweden))")
